DROP TABLE LA_MAYORIA.Datos_Usuario

DROP TABLE LA_MAYORIA.Hotel_Estrellas

DROP TABLE LA_MAYORIA.Usuario_Rol_Hotel

DROP TABLE LA_MAYORIA.Regimen_Hotel

DROP TABLE LA_MAYORIA.Rol_Funcionalidad

DROP TABLE LA_MAYORIA.Historial_Baja_Hotel

DROP TABLE LA_MAYORIA.Historial_Baja_Habitacion

DROP TABLE LA_MAYORIA.Historial_Cancelacion_Reserva

DROP TABLE LA_MAYORIA.Consumible_Reserva

DROP TABLE LA_MAYORIA.Facturacion_Detalle

DROP TABLE LA_MAYORIA.Forma_Pago

--PRINCIPALES/BASE
DROP TABLE LA_MAYORIA.Tipo_Pago

DROP TABLE LA_MAYORIA.Detalle_Tarjeta

DROP TABLE LA_MAYORIA.Facturacion

DROP TABLE LA_MAYORIA.Reserva_Cliente

DROP TABLE LA_MAYORIA.Clientes

DROP TABLE LA_MAYORIA.Nacionalidad

DROP TABLE LA_MAYORIA.Tipo_Identificacion

DROP TABLE LA_MAYORIA.Funcionalidad

DROP TABLE LA_MAYORIA.Habitacion_Reserva

DROP TABLE LA_MAYORIA.Estadia

DROP TABLE LA_MAYORIA.Reserva

DROP TABLE LA_MAYORIA.Regimen

DROP TABLE LA_MAYORIA.Consumible

DROP TABLE LA_MAYORIA.Habitacion

DROP TABLE LA_MAYORIA.Tipo_Habitacion

DROP TABLE LA_MAYORIA.Estado_Reserva

DROP TABLE LA_MAYORIA.Rol

DROP TABLE LA_MAYORIA.Hotel

DROP TABLE LA_MAYORIA.Estrellas

DROP TABLE LA_MAYORIA.Frente

DROP TABLE LA_MAYORIA.Usuario

DROP SCHEMA LA_MAYORIA