DROP TABLE LA_MINORIA.Datos_Usuario

DROP TABLE LA_MINORIA.Usuario_Hotel

DROP TABLE LA_MINORIA.Hotel_Estrellas

DROP TABLE La_MINORIA.Usuario_Rol

DROP TABLE LA_MINORIA.Rol_Funcionalidad

DROP TABLE LA_MINORIA.Funcionalidad

DROP TABLE LA_MINORIA.Rol

DROP TABLE LA_MINORIA.Hotel

DROP TABLE LA_MINORIA.Usuario

DROP SCHEMA LA_MINORIA