DROP PROCEDURE LA_MAYORIA.sp_login_check_valid_user

DROP PROCEDURE LA_MAYORIA.sp_login_check_password

DROP PROCEDURE LA_MAYORIA.sp_rol_exist_one_by_user

DROP PROCEDURE LA_MAYORIA.sp_menu_list_functionality_by_user