DROP PROCEDURE LA_MAYORIA.sp_login_check_valid_user

DROP PROCEDURE LA_MAYORIA.sp_login_check_password

DROP PROCEDURE LA_MAYORIA.sp_rol_exist_one_by_user

DROP PROCEDURE LA_MAYORIA.sp_hotel_exist_one_by_user

DROP PROCEDURE LA_MAYORIA.sp_menu_list_functionality_by_user

DROP PROCEDURE LA_MAYORIA.sp_user_search

DROP PROCEDURE LA_MAYORIA.sp_user_enable_disable

DROP PROCEDURE LA_MAYORIA.sp_user_clean_login

DROP PROCEDURE LA_MAYORIA.sp_user_data_get_by_user

DROP PROCEDURE LA_MAYORIA.sp_user_search_rol_hotel_by_user

DROP PROCEDURE LA_MAYORIA.sp_user_save_update

DROP PROCEDURE LA_MAYORIA.sp_rol_search

DROP PROCEDURE LA_MAYORIA.sp_rol_enable_disable

DROP PROCEDURE LA_MAYORIA.sp_rol_functionality_availability

DROP PROCEDURE LA_MAYORIA.sp_rol_functionality_enabled

DROP PROCEDURE LA_MAYORIA.sp_rol_create

DROP PROCEDURE LA_MAYORIA.sp_rol_functionality_add

DROP PROCEDURE LA_MAYORIA.sp_rol_functionality_remove

DROP PROCEDURE LA_MAYORIA.sp_client_search

DROP PROCEDURE LA_MAYORIA.sp_client_enable_disable

DROP PROCEDURE LA_MAYORIA.sp_client_data_get_by_id_client

DROP PROCEDURE LA_MAYORIA.sp_client_save_update

DROP PROCEDURE LA_MAYORIA.sp_client_check_exist_mail

DROP PROCEDURE LA_MAYORIA.sp_client_check_exist_document

DROP PROCEDURE LA_MAYORIA.sp_hotel_search

DROP PROCEDURE LA_MAYORIA.sp_hotel_regimen_available

DROP PROCEDURE LA_MAYORIA.sp_hotel_regimen_assign

DROP PROCEDURE LA_MAYORIA.sp_hotel_data_get_by_id

DROP PROCEDURE LA_MAYORIA.sp_hotel_save_update

DROP PROCEDURE LA_MAYORIA.sp_hotel_regimen_add

DROP PROCEDURE LA_MAYORIA.sp_hotel_regimen_remove

DROP PROCEDURE LA_MAYORIA.sp_hotel_close_period_valid

DROP PROCEDURE LA_MAYORIA.sp_habitacion_search

DROP PROCEDURE LA_MAYORIA.sp_habitacion_close_period_valid

DROP PROCEDURE LA_MAYORIA.sp_habitacion_exist_hotel_room

DROP PROCEDURE LA_MAYORIA.sp_habitacion_data_get_by_id

DROP PROCEDURE LA_MAYORIA.sp_habitacion_save_update

DROP PROCEDURE LA_MAYORIA.sp_habitacion_person_per_room_by_booking_id

DROP PROCEDURE LA_MAYORIA.sp_regimen_search

DROP PROCEDURE LA_MAYORIA.sp_cancelacion_reserva_search

DROP PROCEDURE LA_MAYORIA.sp_cancelacion_reserva_cancel

DROP PROCEDURE LA_MAYORIA.sp_estadia_booking_search

DROP PROCEDURE LA_MAYORIA.sp_estadia_booking_is_exist

DROP PROCEDURE LA_MAYORIA.sp_estadia_booking_is_cancel

DROP PROCEDURE LA_MAYORIA.sp_estadia_booking_is_hotel

DROP PROCEDURE LA_MAYORIA.sp_estadia_booking_is_before

DROP PROCEDURE LA_MAYORIA.sp_estadia_generate_stay

DROP PROCEDURE LA_MAYORIA.sp_estadia_cancel_is_after_date_check_in

DROP PROCEDURE LA_MAYORIA.sp_estadia_is_for_check_in

DROP PROCEDURE LA_MAYORIA.sp_estadia_exist_full_stay

DROP PROCEDURE LA_MAYORIA.sp_check_client_search

DROP PROCEDURE LA_MAYORIA.sp_estadia_save_stay_client

DROP PROCEDURE LA_MAYORIA.sp_consumibles_estadias_search

DROP PROCEDURE LA_MAYORIA.sp_consumible_filter

DROP PROCEDURE LA_MAYORIA.sp_consumible_by_estadia_search

DROP PROCEDURE LA_MAYORIA.sp_estadia_consumible_add

DROP PROCEDURE LA_MAYORIA.sp_estadia_consumible_remove