DROP TABLE LA_MINORIA.Datos_Usuario

DROP TABLE LA_MINORIA.Usuario_Hotel

DROP TABLE LA_MINORIA.Hotel_Estrellas

DROP TABLE LA_MINORIA.Usuario_Rol

DROP TABLE LA_MINORIA.Rol_Funcionalidad

DROP TABLE LA_MINORIA.Regimen_Hotel

DROP TABLE LA_MINORIA.Historial_Baja_Hotel

DROP TABLE LA_MINORIA.Historial_Baja_Habitacion

DROP TABLE LA_MINORIA.Historial_Cancelacion_Reserva

DROP TABLE LA_MINORIA.Estadia

DROP TABLE LA_MINORIA.Consumible_Reserva

DROP TABLE LA_MINORIA.Facturacion_Detalle

DROP TABLE LA_MINORIA.Forma_Pago

--PRINCIPALES/BASE
DROP TABLE LA_MINORIA.Tipo_Pago

DROP TABLE LA_MINORIA.Detalle_Tarjeta

DROP TABLE LA_MINORIA.Facturacion

DROP TABLE LA_MINORIA.Reserva_Cliente

DROP TABLE LA_MINORIA.Clientes

DROP TABLE LA_MINORIA.Nacionalidad

DROP TABLE LA_MINORIA.Tipo_Identificacion

DROP TABLE LA_MINORIA.Funcionalidad

DROP TABLE LA_MINORIA.Habitacion_Reserva

DROP TABLE LA_MINORIA.Reserva

DROP TABLE LA_MINORIA.Regimen

DROP TABLE LA_MINORIA.Consumible

DROP TABLE LA_MINORIA.Habitacion

DROP TABLE LA_MINORIA.Tipo_Habitacion

DROP TABLE LA_MINORIA.Estado_Reserva

DROP TABLE LA_MINORIA.Rol

DROP TABLE LA_MINORIA.Hotel

DROP TABLE LA_MINORIA.Usuario

DROP SCHEMA LA_MINORIA